name: traccar_manager
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.7.0
  extra_pedantic: ^1.1.1+3
  fluxmap: ^0.2.0
  map_controller: ^0.6.1
  geopoint_location: ^0.4.0
  fluttertoast: ^3.1.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  